### PR TITLE
[BOOST-4687]: add viability tests for swapping on a specific dex

### PR DESCRIPTION
**Pull request by mmackz**
### Description

- Test for swapping on a specific dex (paraswap) on a specific chain (arbitrum)

### CODE REVIEW

**Review by sammccord — APPROVED** [review]

**Comment by Quazia** [comment]
@mmackz Is this blocked or can we get this upstream?

**Comment by mmackz** [comment]
> @mmackz Is this blocked or can we get this upstream?

It should be good, but I ran into some issues with the hardhat config. Not sure how to get it working after the changes yesterday. Im getting an error `The current chain of the wallet (id: 8453) does not match the target chain for the transaction (id: 31337 – undefined).`

**Comment by mmackz** [comment]
Also I cannot find anything suitable to match with the actionClaimant now that we can only target event args and not topics.

**Comment by mmackz** [comment]
Switch the event to use Paraswap instead of aerodrome.

Reason being that we will already cover the uniswap usecase in a different test (hopefully) and aerodrome is a direct clone of uniswap V3.

Also was not able to get the claimant on uniswap/aerodrome without having context of the token addresses. (ie: swap any token on uniswap/aerodrome)

**Pull request merged**
